### PR TITLE
first pass pgp

### PR DESCRIPTION
**Pull request by djcrabhat**
so this is kinda unintelligent right now.  only configurable is GPG_BINARY, but it'll just use the default of the running user's homedir to find the keyring.  You can pack up any format you want in there, as i use seria again to unpack whatever's in a key called "_secret".  (you could do xml inside of yaml, horror of horrors)

```
echo "{\"test\":\"shh\"}"  | gpg --encrypt --armor -r KEY_ID
```

(if saving to json, you'll need to escape all those newlines)

### CODE REVIEW

**Comment by djcrabhat** [comment]
So I cleaned this up a little bit.  You can now set a FIGGY_GPG_BINARY and a FIGGY_GPG_HOME (wanted to use more obvious "this is for figgypy" environment variable names).  Also added a test key pair, store some config in there, then test that I can read what's packed in there.

**Comment by theherk** [comment]
Looking good. I should have some time tomorrow morning to look more closely at this. Thank you for the contributions.

**Comment by theherk** [comment]
I made some modifications, that I think you'll like. Thank you for doing all the heavy lifting. I made it so that you can set these variables inline and they'll be decrypted where they are, rather than having a separate secrets section. Check out the README and commits. Let me know what you think.

**Comment by djcrabhat** [comment]
Oh ya that's much nicer, why force that "secrets" behavior, make it more transparent.  love it!

**Pull request merged**
